Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> def Hammingdistance:
	
SyntaxError: invalid syntax
>>> def Hammingdistance(str1, str2):
	count = 0
	for i in range(len(str1)):
		if str1[1] != str2[i]:
			count += 1
			return count

		
>>> Hammingdistance(AAAAGAATG,AAAAAAAAA)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    Hammingdistance(AAAAGAATG,AAAAAAAAA)
NameError: name 'AAAAGAATG' is not defined
>>> str1 = AAAAAAA
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    str1 = AAAAAAA
NameError: name 'AAAAAAA' is not defined
>>> str1 = (AAAAAAA)
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    str1 = (AAAAAAA)
NameError: name 'AAAAAAA' is not defined
>>> str1 = {AAAAAAA}
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    str1 = {AAAAAAA}
NameError: name 'AAAAAAA' is not defined
>>> 
>>> 
>>> def hammingDistance(p, q):
	ham = 0
	for x, y in zip(p, q):
		if x != y:
			ham += 1
	return ham

>>> hammingDistance(GGGCCGTTGGT, GGACCGTTGAC)
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    hammingDistance(GGGCCGTTGGT, GGACCGTTGAC)
NameError: name 'GGGCCGTTGGT' is not defined
>>> q = (GGACCGTTGAC)
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    q = (GGACCGTTGAC)
NameError: name 'GGACCGTTGAC' is not defined
>>> p={GGACCGTTGAC}
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    p={GGACCGTTGAC}
NameError: name 'GGACCGTTGAC' is not defined
>>> zip(GGGATTTCGGATGAACGGGACAAGGTCACTATGACTGGACGAACTGGCTGCAACAGCGAATAGGTCAGCTCGTTAAATCTGAACAAGTTAGGGCGTAGAGTGCTGGCGAACACTAGTTGGGATCTAGTCTGCGATCGTGGACAGCCACAGAACTTTCATGTTCTCCTACGCCCGCGCTTCACCTGCGATGTGGGGTCGGCGCCCACTGTGCTTCTCGTGGGTTCGGTAATCTTGACCGTATGACGGGCGGAGAAATGAGTCCTACTGAATACACTTTTCTTCAAACAGAACATGCACGCTGTTTTACCTCGGAACTATCAGAATTACTCTACAACTACAAGAAGCAAGAAGAGTAGGGGGATGCGCTATTGTTCATACCTCGTGAAATTCGTACCTTGGGAACACGGCCCCAATGGCAAGGAGGCCGAATCCTTGTGGTGCATATTGGGATTGCCACCATGGCTGAAGGGAGCACGGGTCGGGTTGGCGGCGCGCTGAAAGAGAAAAACGGTCCTCATATCCACGCGCGGGTACTTGGGCGCCGCTCTAGTAGACACCACCCGCTGCGTGTAATGTTCTCTCGTTTAGGCATGGTAGTGTACTCGCGCTGACGATATCGCGACACACGGCTAGGCCACCCTATCAATCCTAACATCAATCAACAGCTAAGTCCGCTAACGCACCTGAGGAAGATGAGCGCGATATGTTAATCGGTATGTTACTGACCCCGGCAATCCTTATATGCCATTTGTACAATCCTCACTTGCGCCTGTCCACTCAGCGTTGTCATTGGCACCTCTAAAGCTTCTCGTGTGAAAACCTATGGGTAGTTCCCGCGATCCCTATAAACTATTCTGCTGGGCCCCATTGGGCCGCTTCCGCTCCGGGACGACATAGTTTTTAGTTGTTCCTAGGCAGTCGGCGTACTCTCCTTACCTGGTCATCGTGCGATAACAGTTATCTTTATCTCATTACACGCAACTCCCTAGCAGGGTTTACAACTGAGTACTGTACGTTCAGACGTTGACGTCACCGGCCCGCTTTATTGTAGTGTAGTACGTCGTAGGCCTCGATACTTGACAATGCATGCA, TTGAGTAGCTATCAGCCTGAGGTCGGACAGACTTGGTATGTTTTCTATGAAGGCTCCAAGGTTAAGCTGGACAATCAGGTTCCGCCGCGTAAGCTCCCCCGCTAGACTCCTACTTGCCTAACCTGCAACTCAGATCTCGTACATTTACGCAACATTCGACAGTGTCCAAGGAACACATTGGCGTCTGGAATACTAATACATGGTATGGTCTCATCTAGGCCTGCTGAATGTCCCAAGAAGTTGACGTAGACCACCCTATCCTAATGTGAACAAAGGTACACTAAAATGACAGCGGTGTTAGGGGAGGAAATCATGCATCACCCCTTCGCCGATAGACGCGACTAAAAGGACACGTTACGGGAATCACGTGCAGGCGTAAAAAGATAACTGCGCAAACGGCGGATATCGCATACTCATTAAGAATGTAGCCATCCATTCAGATTCCCTTTTCTCTAAAGCCAGAAACCGAAGGCGACTTTTCGATGACGAATGAACGCACAATTGCAACCCTACGGCAATTCAGAGACGTTCTCCGATAAGCGATTGACGATCCCCCGAGGTGGGCCTTAGCGATATTGACCTCAGAATTACCACTCCACGAGTCATAAGATTCTCTCCTGCAGAAGATTAAACGTTCCCAACGTCGGCTTGAGCGGTGCTTTTAATGATCGTTCGCTTACCCACAACGCTACTACCATCAAGCACGTGCGTCACGGTTCATTAGCTCCAGAGGTTGGCATAGGTTTGTCTAACGGTCGTCTGATTTGCCCGAGCAGAGTCGTCTCGCCGTCGAGCTGCTCACCTGCTTGGATGTAGGAAAAAACTTAGCTGTCATAGAAGTACTGTGGACATGAAGCTCGATATGGCACGAAAGGCGTGTACAGAAAACGCACGCTACCGTGTTCGCCTGAGCAAAGTAAGTGATGTGCTCGCCTGATGTACAAACACACCAAATAAAACTCTTCTGGGACAGTGAACCAAGGCCGGTTGAGGTACCCCACACCCCCGGGGGTGCACAGGGAACGACAACACTTTACGATCCCCGCTAAGCCTTGCTGCGGGGCACTCAGGAGGCGCGTGTACCGGTCTGT)
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    zip(GGGATTTCGGATGAACGGGACAAGGTCACTATGACTGGACGAACTGGCTGCAACAGCGAATAGGTCAGCTCGTTAAATCTGAACAAGTTAGGGCGTAGAGTGCTGGCGAACACTAGTTGGGATCTAGTCTGCGATCGTGGACAGCCACAGAACTTTCATGTTCTCCTACGCCCGCGCTTCACCTGCGATGTGGGGTCGGCGCCCACTGTGCTTCTCGTGGGTTCGGTAATCTTGACCGTATGACGGGCGGAGAAATGAGTCCTACTGAATACACTTTTCTTCAAACAGAACATGCACGCTGTTTTACCTCGGAACTATCAGAATTACTCTACAACTACAAGAAGCAAGAAGAGTAGGGGGATGCGCTATTGTTCATACCTCGTGAAATTCGTACCTTGGGAACACGGCCCCAATGGCAAGGAGGCCGAATCCTTGTGGTGCATATTGGGATTGCCACCATGGCTGAAGGGAGCACGGGTCGGGTTGGCGGCGCGCTGAAAGAGAAAAACGGTCCTCATATCCACGCGCGGGTACTTGGGCGCCGCTCTAGTAGACACCACCCGCTGCGTGTAATGTTCTCTCGTTTAGGCATGGTAGTGTACTCGCGCTGACGATATCGCGACACACGGCTAGGCCACCCTATCAATCCTAACATCAATCAACAGCTAAGTCCGCTAACGCACCTGAGGAAGATGAGCGCGATATGTTAATCGGTATGTTACTGACCCCGGCAATCCTTATATGCCATTTGTACAATCCTCACTTGCGCCTGTCCACTCAGCGTTGTCATTGGCACCTCTAAAGCTTCTCGTGTGAAAACCTATGGGTAGTTCCCGCGATCCCTATAAACTATTCTGCTGGGCCCCATTGGGCCGCTTCCGCTCCGGGACGACATAGTTTTTAGTTGTTCCTAGGCAGTCGGCGTACTCTCCTTACCTGGTCATCGTGCGATAACAGTTATCTTTATCTCATTACACGCAACTCCCTAGCAGGGTTTACAACTGAGTACTGTACGTTCAGACGTTGACGTCACCGGCCCGCTTTATTGTAGTGTAGTACGTCGTAGGCCTCGATACTTGACAATGCATGCA, TTGAGTAGCTATCAGCCTGAGGTCGGACAGACTTGGTATGTTTTCTATGAAGGCTCCAAGGTTAAGCTGGACAATCAGGTTCCGCCGCGTAAGCTCCCCCGCTAGACTCCTACTTGCCTAACCTGCAACTCAGATCTCGTACATTTACGCAACATTCGACAGTGTCCAAGGAACACATTGGCGTCTGGAATACTAATACATGGTATGGTCTCATCTAGGCCTGCTGAATGTCCCAAGAAGTTGACGTAGACCACCCTATCCTAATGTGAACAAAGGTACACTAAAATGACAGCGGTGTTAGGGGAGGAAATCATGCATCACCCCTTCGCCGATAGACGCGACTAAAAGGACACGTTACGGGAATCACGTGCAGGCGTAAAAAGATAACTGCGCAAACGGCGGATATCGCATACTCATTAAGAATGTAGCCATCCATTCAGATTCCCTTTTCTCTAAAGCCAGAAACCGAAGGCGACTTTTCGATGACGAATGAACGCACAATTGCAACCCTACGGCAATTCAGAGACGTTCTCCGATAAGCGATTGACGATCCCCCGAGGTGGGCCTTAGCGATATTGACCTCAGAATTACCACTCCACGAGTCATAAGATTCTCTCCTGCAGAAGATTAAACGTTCCCAACGTCGGCTTGAGCGGTGCTTTTAATGATCGTTCGCTTACCCACAACGCTACTACCATCAAGCACGTGCGTCACGGTTCATTAGCTCCAGAGGTTGGCATAGGTTTGTCTAACGGTCGTCTGATTTGCCCGAGCAGAGTCGTCTCGCCGTCGAGCTGCTCACCTGCTTGGATGTAGGAAAAAACTTAGCTGTCATAGAAGTACTGTGGACATGAAGCTCGATATGGCACGAAAGGCGTGTACAGAAAACGCACGCTACCGTGTTCGCCTGAGCAAAGTAAGTGATGTGCTCGCCTGATGTACAAACACACCAAATAAAACTCTTCTGGGACAGTGAACCAAGGCCGGTTGAGGTACCCCACACCCCCGGGGGTGCACAGGGAACGACAACACTTTACGATCCCCGCTAAGCCTTGCTGCGGGGCACTCAGGAGGCGCGTGTACCGGTCTGT)
NameError: name 'GGGATTTCGGATGAACGGGACAAGGTCACTATGACTGGACGAACTGGCTGCAACAGCGAATAGGTCAGCTCGTTAAATCTGAACAAGTTAGGGCGTAGAGTGCTGGCGAACACTAGTTGGGATCTAGTCTGCGATCGTGGACAGCCACAGAACTTTCATGTTCTCCTACGCCCGCGCTTCACCTGCGATGTGGGGTCGGC' is not defined
>>> 
>>> 
>>> def hammingDistance(p, q):
	ham = 0
	for x, y in zip(p, q):
		if x != y:
			ham += 1
	return ham

>>> def hammingDistance(p, q):
	ham = 0
	for x, y in zip(p, q):
		if x != y:
			ham += 1
	return ham

def distanceBetweenPatternAndString(pattern, dna):
	k = len(pattern)
	distance = 0
	for x in dna:
		hamming = k+1
		for i in range(len(x) - k + 1):
			z = hammingDistance(pattern, x[i:i+k])
			if hamming > z:
				hamming = z
		distance += hamming
	return distance
SyntaxError: invalid syntax
>>> 
>>> 
>>> def hammingDistance(p, q):
	ham = 0
	for x, y in zip(p, q):
		if x != y:
			ham += 1
	return ham

>>> def distanceBetweenPatternAndString(pattern, dna):
	k = len(pattern)
	distance = 0
	for x in dna:
		hamming = k+1
		for i in range(len(x) - k + 1):
			z = hammingDistance(pattern, x[i:i+k])
			if hamming > z:
				hamming = z
		distance += hamming
	return distance

>>> dna = ["TTACCTTAAC","GATATCTGTC", "ACGGCGTTCG", "CCCTAAAGAG", "CGTCAGAGGT"]
>>> pattern = "AAA"
>>> print(distanceBetweenPatternAndString(pattern, dna))
5
>>> dna = ["ACCTCACATTCACGAGAGTCTAATGTCCAGGGAATACACGCTGCAGGCGCATGGTGTCGCCACCCCGGCCACCGTTAGCGGGATATGGCAATGAG","TAAGAGCTACTTGTCAGTTATCCTGCAGTCAGCATCGCAATGTCTCTTTTGCCTGTAAATCTCTTACTGTCATCATGCTATCACCCCTGCATTCG", "GCACGTAACATTAGCGTGCGTGGTATGAAGCCTAGACCGCTATATCCGCCGGGTCAATTGCAAGACATACGAGAGTACGAGAGTAGCTTGTGCCG","TGGGCGTAGGTGGTACCTTCGGCGCTACGTAAGGAATAGCCTACGATTACAGGGCCCTATATACCGCCGTTACGTACTCCTTGGTTGACCTGGCG","GCAGGCGTTTACTGCATCCCTTCAGATAATGCGAGGTACTGAGCGTGGAGGGCTTTTGGTCCAGATGCGGAGGCTAAGTATATGCTTAGCCCAGT","TATGTCAGCCTCGCAACCGCCAATTCGGCTAGTTCATTTCCGGCCCCTTCGTCACGACAGTGGCTTCGACCAAAAGGGGCATAGAGTGTGTTTCC","CATATCTACATTAGGGTTGTTTAAGCGACTACCCCTCAGGCTTATGGACCCCCATACCGATGTACGGTAGACACGACTGAGTGTCCCTAGATGAT","GAGCCATATAAGGGACTCAGGACACTGGTTTCTCTTACTTTACAGACCCGGATCCCCGGTAGGGCGGATTTTGACCAACAAACCTGTTTAAAGGG","GCGCGTTGAAACCGAATTTTCATCAATAGACTCCGGAGTCTCTTCTTATCCATTTAGACAACCGCGGTTGCGCGTGTCCAAGTTGATACTTGGGA","CATCATTTGGCCGACTTACTCCCGGGCCTGATACAATAAGGGACATTCGATTGATCCAATAACGTCATGAGCTACCGAGCACATATTGAGTCTCA","CCACTTCAGTCATAACGGACGGCATGTCGCTGATTCCATTCAAGGTAAGTCTTCGACCGGCTTCTCAAGCGAGAAACCTAGGCTCCCCATGGGAA","CAGATCTATCGACAAGATAGCACCCGCACTCTCCAAAAAAGAAACGGGGCATCGCCTATTAGGATTCTCATGTAGTAGAGTCGAAGGCTGTGAAT","GCTTGACGCAGCGTAGCATATATGTAGTGGTCTTGTGAGTACAATTGATCCCGTCATCTCTCCCTACCCCGTGCAGTGGAAAGAGGTTCAAATTC","GTCCTTTCCAGCAAGCTGGGCGTCCAGTAGGCGAGCTCTGAAGAAGTTGTCGCCAAACGATTAACTGGCGCAGAAGGATCGTCACGACTACGAAA","TGAGTCACAGAAGAGGTAAAGACCATCTGATTTAAGATCAACAAATCCAAAGCCAGCATCGCTAACGAGGGCAAGACAGACGGATAGGTGATAAC","GCCTATCCACCGGCAGCCAGCTCTTGTGAATAGTTCCCCCAAAAAAGGGGCCTTTTCAGTACATAACTAACCGACATTGCGAGGCGACGGATATG","GTTCTGGCTGCGACGTAAGCAATTATCGTCCCTGACGCCTCATTGTGTGGCGAAATGTTGATTGTGTGTGCAGATCTGTCAGGAGTCATGCTCGG","TCCTAACCCTACCCTATGTTCATCATTGACTATTCTGCATACCCTGCGGACTAGTTACTTACACTGTAACGTCCTGTGCGTTGGCAATTCTGCAC","CCTTCGCTTGATGCCACTGCCACCCCTTAAAAAGGACCCGATGCCTCTGCGGCTATTCCGTTTCACGTCACGCATGAGTTGCAGGCTCAGGTTCA","ACGTTAGCTAAATAATTCACTATACGGCCGTCCCGTTGCTATGTTCCCCTAGTCTACCAAGTTGACTTTGTATGATACGATTGATTGCGGGTTAA","ACGGTGTCCGCAGCCCCAAGACCCCGTCCACTTTTGATTTTATACCCTCAATAGACGCACGACATGCTAATGTCAAAACGCCCAGAAGACGACAC","GACTAACACCATGCGGAGCTGACCTAGGGTCGGATTGTAGCGGTTCTCGAATACACCAAGTCCGTCGAGTTCCTTTAGTGACGGCGCGATCCAAG","CTTGAAGCGCAACCAGATACAGATACTCATATCGGCAAGCCAGACAGATGACGTGCGTCGGCGGCAGTTATGTGTCCCTGCTACTCATCGCTGGC","GCTGTAAGTTTTCTGATACGGGCGGGGCTGTGGTCCAGTCGTTAGTGCACGGCATTTAATGTCACAGATGCAGTCTTACACCGCCCCCTTCGACA","CATTCGTAGAAGGGGTGCTGGGGGCTTCCGTCTACTCCTGCGATTCGTATTTGCTATGTACATGGAGACTTACGGCCTTTGCTATCATCTTAGTA","GTGAGATTCTCTATTAGACGCCTACTCAAGCGGAAGTAACGCGAGTAGCTCTTACGCCGCGAATGAGTTAGAATTCTACATCTATACGACCTCCG","AATCATGTATTACTCATATTGAGTACTATTAACCCACTAATTCCTGCTGTAGTTACTCCTGGACCGCCGCCTAGCGACCTTACAATGGGACGGCG","CGCTTTTTCGCAAATACAACATGCGATTTCACCTCGGGCCCCTAGTCTTGGTGCTGCTCCATCAGGCGTATCTAACTGAGCGCATTTGCTTAAAG","TTACCCTATCGCTCCCATTTCCTTCCTGGGCTAGGGCTCCGAACAGGGGCGACGCGTGTGTCGTAAGCGGACCCCGATGTCCGCAATCAAGGCGC","ACTCTATCAAAGCTTGACTGAGCCCTTTTGAGTGAAGTCTTTGCTGCGTGGCAATTCCATTAGTTACTGAGCTTAATCTGTAGGTGAGTCTTTCC","GAAGTGAAGTTGATACTGCGCTTTCACGGATCATCGGGCTATTAGACTCGATCCCATGACTGCTGACGAGTTGCCTTGTTTATTTTGTAGCGTTA","CGGTGAGACCAGTTATTTTTCAGTATTCACCGTACAGATGATATAGCTCTCCAATGACCTAGGTGGTAAACAGACGTCTGATACGAAGCTTCACC","TTTGCTCGGCCGATATGCAACCGTTTTTAACCAGGTCAACGGAATAGGCTCCACACCTCGAATGATACAAAAAAATGCTTGGAGGACCAGTACCT","CGGGGCTAAAAGTATCTGGCCCTCTACGTACTGATAAGCTTTCGTATCATCTGACCTTAACACGGCCCATAAATAGTTTCGGTCTCGTCTAGAAA"]
>>> pattern = "TCTCTAG"
>>> print(distanceBetweenPatternAndString(pattern, dna))
74
>>> 
